name: eyecon_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  provider: ^5.0.0
  intl: ^0.17.0
  logger: any
  dio: ^4.0.0
  http: any
  toast: any
  carousel_slider: ^3.0.0
  font_awesome_flutter: any
  shared_preferences: ^2.0.5
  sticky_and_expandable_list: ^0.3.1
  flutter_progress_dialog: ^0.1.0
  configurable_expansion_tile: ^1.0.0
  flutter_widget_from_html: ^0.6.1
  flutter_switch: ^0.3.1
  flutter_screenutil: ^5.0.0+2
  device_info: ^2.0.0
  cached_network_image: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  easy_dialog: ^1.0.5
  container_tab_indicator: ^0.2.0
  url_launcher: ^6.0.3
  get_it: ^7.1.3
  flutter_open_whatsapp: ^0.1.2
  imei_plugin: ^1.2.0
  rflutter_alert: ^2.0.2
  flutter_dropdown: ^0.0.8
  ndialog: ^4.1.0
  unique_identifier: ^0.0.3
  pin_code_fields: ^7.1.0
  shape_of_view: ^1.0.2
  back_button_interceptor: ^5.0.0
  timer_count_down: ^2.0.1
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.11.1
  share: ^2.0.1
  flutter_cache_manager: ^3.0.2
  image_downloader: ^0.30.0
  grouped_list: ^4.0.0
  image_picker: ^0.7.5
  my_fatoorah: ^3.0.2
  flutter_webview_plugin: ^0.3.11



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon_login.png
    - lang/ar.json
    - lang/en.json
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
